# Site Settings

#paginate:            5

# Build settings
markdown:            kramdown
kramdown:
  input: GFM

highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap]

includes:
- pages
- research

exclude: [BKP, dependencies.txt]
